Fix wheel error for ci_suit workflow (#56053)
Adds wheel package since its required by some setup.py
Workflow run with this option added: https://github.com/Gamer025/tgstation/pull/1/checks?check_run_id=1672278250

Gets rid of all the
error: invalid command 'bdist_wheel'
errors in the ci_suite workflows
Conflicts:
	.github/workflows/ci_suite.yml
	tools/bootstrap/python